//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Acividad
{
    using System;
    using System.Collections.Generic;
    
    public partial class fruta
    {
        public int id { get; set; }
        public string Nombre { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string Descripcion { get; set; }
        public string Precio { get; set; }
    }
}
